services:
  db:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: saas-starter-kit
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  pga:
    image: dpage/pgadmin4:9.2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: talktopaul@gmail.com
      PGADMIN_DEFAULT_PASSWORD: henkin123
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pga.rule=Host(`pga.henkin.world`)"
      - "traefik.http.routers.pga.entrypoints=websecure"
      - "traefik.http.routers.pga.tls.certresolver=letsencrypt"
      - "traefik.http.services.pga.loadbalancer.server.port=80"
    networks:
      - proxy
      - app_network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "80"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  henkinworld:
    build:
      context: .
      dockerfile: Dockerfile
    image: henkin-world-react:latest 
    restart: always
    depends_on:
      - db
    environment:
      - APP_URL=https://henkin.world
      - AUTH_PROVIDERS=credentials,email,github,google
      - DATABASE_URL=postgresql://admin:admin@db:5432/saas-starter-kit
      - NEXTAUTH_URL=https://henkin.world
      - NEXTAUTH_SECRET="rZTFtfNuSMajLnfFrWT2PZ3lX8WZv7W/Xs2H8hkEY6g="
      - NODE_ENV=production
      - GITHUB_CLIENT_ID=Ov23liAGXacAQKHc6APh
      - GITHUB_CLIENT_SECRET=e8c6918c92faa5cd6a521b6c391a1f9584c5d883
      - GOOGLE_CLIENT_ID=1030176300795-oe9gegpj7bpm6frjqbg91ugjdssg796h.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
    ports:
      - "4002:4002"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.henkinworld.rule=Host(`henkin.world`)"
      - "traefik.http.routers.henkinworld.entrypoints=websecure"
      - "traefik.http.routers.henkinworld.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.henkinworld-http.rule=Host(`henkin.world`)"
      # - "traefik.http.routers.henkinworld-http.entrypoints=web"
      - "traefik.http.services.henkinworld.loadbalancer.server.port=4002"
      # - "traefik.http.routers.henkinworld-http.middlewares=henkin-world-redirect"
      # - "traefik.http.middlewares.henkin-world-redirect.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.henkin-world-redirect.redirectscheme.permanent=true"
      # - "traefik.http.services.henkin-world.loadbalancer.server.scheme=http"
    networks:
      - proxy
      - app_network
    healthcheck:
      test: ["CMD", "nc", "-z", "0.0.0.0", "4002"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  postgres_data:
  pgadmin_data:

networks:
  proxy:
    external: true 
  app_network:
    driver: bridge 