version: '3.8'

services:
  db:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: saas-starter-kit
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  pga:
    image: dpage/pgadmin4:9.2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: talktopaul@gmail.com
      PGADMIN_DEFAULT_PASSWORD: henkin123
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pga.rule=Host(`pga.henkin.world`)"
      - "traefik.http.routers.pga.entrypoints=websecure"
      - "traefik.http.routers.pga.tls.certresolver=letsencrypt"
      - "traefik.http.services.pga.loadbalancer.server.port=80"
    networks:
      - proxy
      - app_network

  henkin-world:
    build:
      context: .
      dockerfile: Dockerfile
    image: henkin-world-react:latest 
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/saas-starter-kit
      - NEXTAUTH_URL=https://henkin.world
      - NEXTAUTH_SECRET="rZTFtfNuSMajLnfFrWT2PZ3lX8WZv7W/Xs2H8hkEY6g="
      - NODE_ENV=production
    ports:
      - "4002:4002"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.henkin-world.rule=Host(`henkin.world`)"
      - "traefik.http.routers.henkin-world.entrypoints=websecure"
      - "traefik.http.routers.henkin-world.tls.certresolver=letsencrypt"
      - "traefik.http.routers.henkin-world-http.rule=Host(`henkin.world`)"
      - "traefik.http.routers.henkin-world-http.entrypoints=web"
      - "traefik.http.routers.henkin-world-http.middlewares=henkin-world-redirect"
      - "traefik.http.middlewares.henkin-world-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.henkin-world-redirect.redirectscheme.permanent=true"
      - "traefik.http.services.henkin-world.loadbalancer.server.port=4002"
      - "traefik.http.services.henkin-world.loadbalancer.server.scheme=http"
    networks:
      - proxy
      - app_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  proxy:
    external: true 
  app_network:
    driver: bridge 